/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-10-24 11:53:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.order;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class orderGoodsForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1695776512350L));
    _jspx_dependants.put("jar:file:/C:/Users/hotjy/Documents/sun-master/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sun/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Users/hotjy/Documents/sun-master/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sun/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!-- 주문자 휴대폰 번호 -->\r\n");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!-- 최종 결제 금액 -->\r\n");
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 총주문 금액 -->\r\n");
      if (_jspx_meth_c_005fset_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!-- 총 상품수 -->\r\n");
      if (_jspx_meth_c_005fset_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!-- 총할인금액 -->\r\n");
      if (_jspx_meth_c_005fset_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!-- 총 배송비 -->\r\n");
      if (_jspx_meth_c_005fset_005f6(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("	<div class=\"row ms-5 ps-5\">\r\n");
      out.write("		<div class=\"mt-5 p-0 ps-5 align-items-center\">\r\n");
      out.write("			<form name=\"form_order\">\r\n");
      out.write("				<div class=\"ps-4\">\r\n");
      out.write("					<p class=\"fs-5 fw-bold mb-3\">주문하기</p>\r\n");
      out.write("					<div class=\"border-top border-main border-2 mt-2\">\r\n");
      out.write("						<div class=\"shadow-sm p-4 pt-2 mt-3 rounded border border-light\">\r\n");
      out.write("\r\n");
      out.write("							<!-- myOrderList를 돌려 각 주문상품 정보를 표시한다. -->\r\n");
      out.write("							");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("							<!-- myOrderList를 돌려 각 주문상품 정보를 표시한다. -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<!-- 주문상품 총 금액 계산 -->\r\n");
      out.write("							<p\r\n");
      out.write("								class=\"bg-light border text-end p-3 text-secondary d-flex justify-content-end align-items-center mt-4\">\r\n");
      out.write("								<span> \r\n");
      out.write("								\r\n");
      out.write("								<!-- 총 상품가격 --> \r\n");
      out.write("								<span>총 상품가격 <span id=\"p_totalPrice\">\r\n");
      out.write("								");
      if (_jspx_meth_fmt_005fformatNumber_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("								</span>원</span> \r\n");
      out.write("								<input id=\"h_totalPrice\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${total_order_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> \r\n");
      out.write("								<!-- 총 상품가격 --> \r\n");
      out.write("								\r\n");
      out.write("								<!-- 총 배송비 -->\r\n");
      out.write("									<span>+</span> <span>총 배송비 0원</span> \r\n");
      out.write("								<!-- 총 배송비 --> \r\n");
      out.write("								\r\n");
      out.write("								<!-- 총 주문금액 -->\r\n");
      out.write("									<span>=</span> 총 주문금액</span> <span class=\"text-black fw-bold fs-5 ms-3\">\r\n");
      out.write("									<span id=\"p_final_totalPrice\">\r\n");
      out.write("									");
      if (_jspx_meth_fmt_005fformatNumber_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("									\r\n");
      out.write("									</span>원</span> \r\n");
      out.write("									<input id=\"h_final_total_Price\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${final_total_order_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("								<!-- 총 주문금액 -->\r\n");
      out.write("\r\n");
      out.write("							</p>\r\n");
      out.write("							<!-- 주문상품 총 금액 계산 -->\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<p class=\"mt-5 mb-3 fw-bold\">배송지</p>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"table-responsive\">\r\n");
      out.write("					\r\n");
      out.write("					<!-- 기본 회원정보를 valuㄷ로 지정한다. -->\r\n");
      out.write("						<table class=\"table border-top mb-0 small fw-light\">\r\n");
      out.write("							<tbody>\r\n");
      out.write("\r\n");
      out.write("							<!-- 이름 -->\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td class=\"table-light ps-4 align-middle\" style=\"width: 200px;\">이름</td>\r\n");
      out.write("									<td class=\"px-4\"><input class=\"form-control rounded-0\" required\r\n");
      out.write("										id=\"receiver_name\" name=\"receiver_name\" type=\"text\" size=\"40\"\r\n");
      out.write("										value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderer.member_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"width: 300px;\">\r\n");
      out.write("										<input type=\"hidden\" id=\"h_orderer_name\" name=\"h_orderer_name\"\r\n");
      out.write("										value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderer.member_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> <input type=\"hidden\"\r\n");
      out.write("										id=\"h_receiver_name\" name=\"h_receiver_name\"\r\n");
      out.write("										value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderer.member_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<!-- 이름 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("								<!-- 휴대폰 -->\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td class=\"table-light ps-4 align-middle\" style=\"width: 200px;\">휴대폰\r\n");
      out.write("										번호</td>\r\n");
      out.write("									<td class=\"px-4\"><input class=\"form-control rounded-0\" required\r\n");
      out.write("										type=\"text\" id=\"hp1\" name=\"hp1\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderer.hp1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("										style=\"width: 300px;\"> <input type=\"hidden\" id=\"h_hp1\"\r\n");
      out.write("										name=\"h_hp1\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderer.hp1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> ");
      if (_jspx_meth_c_005fset_005f10(_jspx_page_context))
        return;
      out.write("</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<!-- 휴대폰 -->\r\n");
      out.write("\r\n");
      out.write("								<!-- 배송지 -->\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td class=\"table-light ps-4 align-middle\" style=\"width: 200px;\">배송지</td>\r\n");
      out.write("									<td class=\"px-4\">\r\n");
      out.write("										<div class=\"input-group mb-2\" style=\"width: 395px;\">\r\n");
      out.write("											<input class=\"form-control rounded-0\" type=\"text\"\r\n");
      out.write("												id=\"zipcode\" name=\"zipcode\" size=\"5\"\r\n");
      out.write("												value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderer.zipcode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" aria-describedby=\"button-addon2\" required>\r\n");
      out.write("											<a class=\"btn border-main small rounded-0 samll\"\r\n");
      out.write("												type=\"button\" id=\"button-addon2\"\r\n");
      out.write("												href=\"javascript:execDaumPostcode()\">우편번호 검색</a>\r\n");
      out.write("										</div> <input class=\"form-control rounded-0 mb-2\" type=\"text\"\r\n");
      out.write("										id=\"member_address\" name=\"member_address\" size=\"50\"\r\n");
      out.write("										value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderer.member_address }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required> <input\r\n");
      out.write("										class=\"form-control rounded-0\" type=\"text\" id=\"subaddress\"\r\n");
      out.write("										name=\"subaddress\" size=\"50\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderer.subaddress }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\r\n");
      out.write("\r\n");
      out.write("										<input type=\"hidden\" id=\"h_zipcode\" name=\"h_zipcode\"\r\n");
      out.write("										value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderer.zipcode }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  /> <input type=\"hidden\"\r\n");
      out.write("										id=\"h_member_address\" name=\"h_zipcode\"\r\n");
      out.write("										value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderer.member_address }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> <input type=\"hidden\"\r\n");
      out.write("										id=\"h_subaddress\" name=\"h_zipcode\"\r\n");
      out.write("										value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderer.subaddress }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<!-- 배송지 -->\r\n");
      out.write("								\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("						<!-- 기본 회원정보를 valuㄷ로 지정한다. -->\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<!-- 결제방법 선택 -->\r\n");
      out.write("					<p class=\"mt-5 mb-3 fw-bold\">결제정보</p>\r\n");
      out.write("					<table class=\"table border-top mb-0 small fw-light\">\r\n");
      out.write("						<tbody>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"table-light ps-4 align-middle\" style=\"width: 200px;\">\r\n");
      out.write("									결제방법</td>\r\n");
      out.write("								<td class=\"\">\r\n");
      out.write("								\r\n");
      out.write("								<div class=\"row px-4\">\r\n");
      out.write("								\r\n");
      out.write("								<div class=\"form-check col-3\">\r\n");
      out.write("								  <input class=\"form-check-input\" type=\"radio\" name=\"pay_method\" id=\"pay1\" value=\"신용카드\" checked>\r\n");
      out.write("								  <label class=\"form-check-label\" for=\"pay1\">\r\n");
      out.write("								    신용카드\r\n");
      out.write("								  </label>\r\n");
      out.write("								</div>\r\n");
      out.write("								\r\n");
      out.write("								<!-- <div class=\"form-check col-3\">\r\n");
      out.write("								  <input class=\"form-check-input\" type=\"radio\" name=\"pay_method\" id=\"pay2\" value=\"제휴 신용카드\">\r\n");
      out.write("								  <label class=\"form-check-label\" for=\"pay2\">\r\n");
      out.write("								    제휴 신용카드\r\n");
      out.write("								  </label>\r\n");
      out.write("								</div> -->\r\n");
      out.write("								\r\n");
      out.write("								<!-- <div class=\"form-check col-3\">\r\n");
      out.write("								  <input class=\"form-check-input\" type=\"radio\" name=\"pay_method\" id=\"pay3\" value=\"실시간 계좌이체\">\r\n");
      out.write("								  <label class=\"form-check-label\" for=\"pay3\">\r\n");
      out.write("								    실시간 계좌이체\r\n");
      out.write("								  </label>\r\n");
      out.write("								</div> -->\r\n");
      out.write("								\r\n");
      out.write("								<!-- <div class=\"form-check col-3\">\r\n");
      out.write("								  <input class=\"form-check-input\" type=\"radio\" name=\"pay_method\" id=\"pay4\" value=\"무통장 입금\">\r\n");
      out.write("								  <label class=\"form-check-label\" for=\"pay4\">\r\n");
      out.write("								    무통장 입금\r\n");
      out.write("								  </label>\r\n");
      out.write("								</div> -->\r\n");
      out.write("								\r\n");
      out.write("								<div class=\"form-check col-3\">\r\n");
      out.write("								  <input class=\"form-check-input\" type=\"radio\" name=\"pay_method\" id=\"pay5\" value=\"휴대폰결제\">\r\n");
      out.write("								  <label class=\"form-check-label\" for=\"pay5\">\r\n");
      out.write("								    휴대폰결제\r\n");
      out.write("								  </label>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"form-check col-3\">\r\n");
      out.write("									<input class=\"form-check-input\" type=\"radio\" name=\"pay_method\" id=\"pay6\" value=\"카카오페이(간편결제)\">\r\n");
      out.write("									<label class=\"form-check-label\" for=\"pay6\">\r\n");
      out.write("									  카카오페이(간편결제)\r\n");
      out.write("									</label>\r\n");
      out.write("								  </div>\r\n");
      out.write("								  \r\n");
      out.write("								  <div class=\"form-check col-3\">\r\n");
      out.write("									<input class=\"form-check-input\" type=\"radio\" name=\"pay_method\" id=\"pay7\" value=\"네이버페이(카드)\">\r\n");
      out.write("									<label class=\"form-check-label\" for=\"pay7\">\r\n");
      out.write("									  네이버페이(카드)\r\n");
      out.write("									</label>\r\n");
      out.write("								  </div>\r\n");
      out.write("\r\n");
      out.write("								  <div class=\"form-check col-3\">\r\n");
      out.write("									<input class=\"form-check-input\" type=\"radio\" name=\"pay_method\" id=\"pay8\" value=\"네이버페이(포인트)\">\r\n");
      out.write("									<label class=\"form-check-label\" for=\"pay8\">\r\n");
      out.write("									  네이버페이(포인트)\r\n");
      out.write("									</label>\r\n");
      out.write("								  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("								 <!--  <div class=\"form-check col-3\">\r\n");
      out.write("									<input class=\"form-check-input\" type=\"radio\" name=\"pay_method\" id=\"pay9\" value=\"직접입금\">\r\n");
      out.write("									<label class=\"form-check-label\" for=\"pay9\">\r\n");
      out.write("									  직접입금\r\n");
      out.write("									</label>\r\n");
      out.write("								  </div> -->\r\n");
      out.write("								\r\n");
      out.write("								</div>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("							<!-- 카드결제 form -->\r\n");
      out.write("							<tr class=\"whenSelected_Card\">\r\n");
      out.write("								<td class=\"table-light ps-4 align-middle\" style=\"width: 200px;\">\r\n");
      out.write("								<p class=\"mb-2\">카드결제정보</p>\r\n");
      out.write("								<p class=\"text-danger small cardFormError mb-0 d-none\"><span class=\"fw-bold\">*입력정보를 확인해주세요</span><br>\r\n");
      out.write("								유효기간과(월/년), 비밀번호는 2자리 숫자로, <br>\r\n");
      out.write("								생년월일은 6자리 숫자로 입력하셔야합니다.\r\n");
      out.write("								</p>\r\n");
      out.write("								</td>\r\n");
      out.write("								<td class=\"px-4\">\r\n");
      out.write("									<div class=\"d-flex align-items-center mb-2\">\r\n");
      out.write("										<div style=\"width:100px\"><p class=\"mb-0\">카드사 선택</p></div>\r\n");
      out.write("										<div>\r\n");
      out.write("											<select id=\"\" name=\"\" class=\"form-select rounded-0\" style=\"width: 300px;\" onchange=\"selectValue(this, this.value)\">\r\n");
      out.write("												<option value=\"삼성\" selected>삼성</option>\r\n");
      out.write("												<option value=\"하나SK\">하나SK</option>\r\n");
      out.write("												<option value=\"현대\">현대</option>\r\n");
      out.write("												<option value=\"KB\">KB</option>\r\n");
      out.write("												<option value=\"신한\">신한</option>\r\n");
      out.write("												<option value=\"롯데\">롯데</option>\r\n");
      out.write("												<option value=\"BC\">BC</option>\r\n");
      out.write("												<option value=\"시티\">시티</option>\r\n");
      out.write("												<option value=\"NH농협\">NH농협</option>\r\n");
      out.write("										</select>\r\n");
      out.write("										<input type=\"hidden\" id=\"card_com_name\" name=\"card_com_name\" value=\"삼성\">\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"d-flex align-items-center mb-2\">\r\n");
      out.write("										<div style=\"width:100px\"><p class=\"mb-0\">할부기간</p>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div>\r\n");
      out.write("											<select id=\"\" name=\"\" class=\"form-select rounded-0\" style=\"width: 300px;\" onchange=\"selectValue(this, this.value)\">\r\n");
      out.write("												<option value=\"0\" selected>일시불</option>\r\n");
      out.write("												<option value=\"2\">2개월</option>\r\n");
      out.write("												<option value=\"3\">3개월</option>\r\n");
      out.write("												<option value=\"4\">4개월</option>\r\n");
      out.write("												<option value=\"5\">5개월</option>\r\n");
      out.write("												<option value=\"6\">6개월</option>\r\n");
      out.write("										</select>\r\n");
      out.write("										<input type=\"hidden\" id=\"card_pay_month\" name=\"card_pay_month\" value=\"0\">\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("									<div class=\"d-flex align-items-center mb-2\">\r\n");
      out.write("										<div style=\"width: 100px\">\r\n");
      out.write("											<p class=\"mb-0\">카드번호</p>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div>\r\n");
      out.write("											<input type=\"text\" id=\"cardNum\" name=\"cardNum\"\r\n");
      out.write("												class=\"form-control rounded-0\" style=\"width: 300px;\"\r\n");
      out.write("												value=\"\" placeholder=\"-를 제외하고 적어주세요\" required/>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									\r\n");
      out.write("									<div class=\"d-flex align-items-center mb-2\">\r\n");
      out.write("										<div style=\"width: 100px\">\r\n");
      out.write("											<p class=\"mb-0\">유효기간</p>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"input-group\"  style=\"width: 300px;\">\r\n");
      out.write("										<div>\r\n");
      out.write("										\r\n");
      out.write("										</div>\r\n");
      out.write("											<input type=\"text\" id=\"cardDate_month\" name=\"cardDate_month\"\r\n");
      out.write("												class=\"form-control rounded-0\" style=\"width: 50px;\"\r\n");
      out.write("												value=\"\" placeholder=\"00(월)\" onBlur=\"checkLength(this, 2);\" maxlength=\"2\"/>\r\n");
      out.write("												<span class=\"py-1 px-3\"> / </span>\r\n");
      out.write("												<input type=\"text\" id=\"cardDate_year\" name=\"cardDate_year\"\r\n");
      out.write("												class=\"form-control rounded-0\" style=\"width: 50px;\"\r\n");
      out.write("												value=\"\" placeholder=\"00(년)\" onBlur=\"checkLength(this, 2);\" maxlength=\"2\"/>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									\r\n");
      out.write("									<div class=\"d-flex align-items-center mb-2\">\r\n");
      out.write("										<div style=\"width: 100px\">\r\n");
      out.write("											<p class=\"mb-0\">생년월일</p>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div>\r\n");
      out.write("											<input type=\"text\" id=\"birth\" name=\"birth\"\r\n");
      out.write("												class=\"form-control rounded-0\" style=\"width: 300px;\"\r\n");
      out.write("												value=\"\"  placeholder=\"6자리로 작성해주세요 예) 980314\"\r\n");
      out.write("												 onBlur=\"checkLength(this, 6)\" maxlength=\"6\"/>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									\r\n");
      out.write("									<div class=\"d-flex align-items-center mb-2\">\r\n");
      out.write("										<div style=\"width: 100px\">\r\n");
      out.write("											<p class=\"mb-0\">비밀번호</p>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div>\r\n");
      out.write("											<input type=\"text\" id=\"cardPassword\" name=\"cardPassword\"\r\n");
      out.write("												class=\"form-control rounded-0\" style=\"width: 300px;\"\r\n");
      out.write("												value=\"\" placeholder=\"비밀번호 앞 2자리\"\r\n");
      out.write("												 onBlur=\"checkLength(this, 2)\" maxlength=\"2\" required/>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<!-- 카드결제 form -->\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("							<!-- 휴대폰결제 form -->\r\n");
      out.write("							<tr class=\"whenSelected_Phone d-none\">\r\n");
      out.write("								<td class=\"table-light ps-4 align-middle\" style=\"width: 200px;\">휴대폰 번호</td>\r\n");
      out.write("								<td class=\"px-4\">\r\n");
      out.write("								<input class=\"form-control rounded-0\" type=\"text\" id=\"pay_orderer_hp_num\" name=\"pay_order_tel\" value=\"\" placeholder=\"-없이 작성해주세요: 01000000000\" style=\"width: 300px;\">\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<!-- 휴대폰결제 form -->\r\n");
      out.write("							\r\n");
      out.write("						</tbody>\r\n");
      out.write("					</table>\r\n");
      out.write("					\r\n");
      out.write("					<!-- 결제방법 선택 -->\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					<!-- 결제하기-->\r\n");
      out.write("					<a name=\"btn_process_pay_order\" onClick=\"fn_process_pay_order()\"\r\n");
      out.write("						class=\"btn btn-lg btn-main rounded-0 w-100 d-block fw-bold p-2 lh-lg mt-5 mb-2\">결제하기</a>\r\n");
      out.write("						\r\n");
      out.write("					<!-- 결제하기-->\r\n");
      out.write("\r\n");
      out.write("					<!-- 취소하기, 메인페이지로 돌아간다.-->\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main/main.do\"\r\n");
      out.write("						class=\"btn btn-lg border-main rounded-0 w-100 d-block fw-bold p-2 lh-lg mt-0 mb-3 fs-6\">취소하기</a>\r\n");
      out.write("					<!-- 취소하기, 메인페이지로 돌아간다.-->\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form name=\"order_info\" method=\"post\" accept-charset=\"euc-kr\">\r\n");
      out.write("<input type=\"hidden\" name=\"ordr_idxx\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ordr_idxx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"good_name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ good_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"good_mny\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ good_mny }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"buyr_name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ buyr_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"site_cd\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ site_cd }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<!-- 고정값 --> \r\n");
      out.write("<input type=\"hidden\" name=\"req_tx\" value=\"pay\">\r\n");
      out.write("<input type=\"hidden\" name=\"pay_method\" value=\"100000000000\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"currency\" value=\"410\">\r\n");
      out.write("\r\n");
      out.write("<!-- 결제수단 값  -->\r\n");
      out.write("<input type=\"hidden\" name=\"kakaopay_direct\" value=\"\" class=\"easyPayment_method\">\r\n");
      out.write("<input type=\"hidden\" name=\"naverpay_direct\" value=\"\" class=\"easyPayment_method\">\r\n");
      out.write("<input type=\"hidden\" name=\"naverpay_point_direct\" value=\"\" class=\"easyPayment_method\">\r\n");
      out.write("<!-- 결제수단 값  -->\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" name=\"module_type\" value=\"01\"/>\r\n");
      out.write("<!-- 주문정보 검증 관련 정보 : 표준웹 에서 설정하는 정보입니다 -->\r\n");
      out.write("<input type=\"hidden\" name=\"ordr_chk\" value=\"\"/>\r\n");
      out.write("<!-- 추가파라미터(가맹점에서 별도의 값 전달시 param_opt를 사용하여 값 전달 -->\r\n");
      out.write("<input type=\"hidden\" name=\"param_opt_1\" value=\"\">\r\n");
      out.write("<input type=\"hidden\" name=\"param_opt_2\" value=\"\">\r\n");
      out.write("<input type=\"hidden\" name=\"param_opt_3\" value=\"\">\r\n");
      out.write("\r\n");
      out.write("<!-- ※ 필 수\r\n");
      out.write("필수 항목 : 표준웹에서 값을 설정하는 부분으로 반드시 포함되어야 합니다\r\n");
      out.write("값을 설정하지 마십시오 -->\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" name=\"res_cd\" value=\"\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"res_msg\" value=\"\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"enc_info\" value=\"\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"enc_data\" value=\"\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"ret_pay_method\" value=\"\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"tran_cd\" value=\"\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"use_pay_method\" value=\"\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"card_pay_method\" value=\"\"/>\r\n");
      out.write("</form>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/order.js\"></script>	\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://pay.kcp.co.kr/plugin/payplus_web.jsp\"></script>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/order/orderGoodsForm.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/order/orderGoodsForm.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/order/orderGoodsForm.jsp(5,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/order/orderGoodsForm.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("orderer_hp");
      // /WEB-INF/views/order/orderGoodsForm.jsp(7,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/order/orderGoodsForm.jsp(7,0) ''",_jsp_getExpressionFactory().createValueExpression("",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/views/order/orderGoodsForm.jsp(9,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("final_total_order_price");
      // /WEB-INF/views/order/orderGoodsForm.jsp(9,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/order/orderGoodsForm.jsp(9,0) '0'",_jsp_getExpressionFactory().createValueExpression("0",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f3_reused = false;
    try {
      _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f3.setParent(null);
      // /WEB-INF/views/order/orderGoodsForm.jsp(12,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setVar("total_order_price");
      // /WEB-INF/views/order/orderGoodsForm.jsp(12,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/order/orderGoodsForm.jsp(12,0) '0'",_jsp_getExpressionFactory().createValueExpression("0",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
      if (_jspx_th_c_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
      _jspx_th_c_005fset_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f4 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f4_reused = false;
    try {
      _jspx_th_c_005fset_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f4.setParent(null);
      // /WEB-INF/views/order/orderGoodsForm.jsp(14,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f4.setVar("total_order_goods_qty");
      // /WEB-INF/views/order/orderGoodsForm.jsp(14,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f4.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/order/orderGoodsForm.jsp(14,0) '0'",_jsp_getExpressionFactory().createValueExpression("0",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f4 = _jspx_th_c_005fset_005f4.doStartTag();
      if (_jspx_th_c_005fset_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f4);
      _jspx_th_c_005fset_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f5 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f5_reused = false;
    try {
      _jspx_th_c_005fset_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f5.setParent(null);
      // /WEB-INF/views/order/orderGoodsForm.jsp(16,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f5.setVar("total_discount_price");
      // /WEB-INF/views/order/orderGoodsForm.jsp(16,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f5.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/order/orderGoodsForm.jsp(16,0) '0'",_jsp_getExpressionFactory().createValueExpression("0",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f5 = _jspx_th_c_005fset_005f5.doStartTag();
      if (_jspx_th_c_005fset_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f5);
      _jspx_th_c_005fset_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f6 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f6_reused = false;
    try {
      _jspx_th_c_005fset_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f6.setParent(null);
      // /WEB-INF/views/order/orderGoodsForm.jsp(18,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f6.setVar("total_delivery_price");
      // /WEB-INF/views/order/orderGoodsForm.jsp(18,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f6.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/order/orderGoodsForm.jsp(18,0) '0'",_jsp_getExpressionFactory().createValueExpression("0",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f6 = _jspx_th_c_005fset_005f6.doStartTag();
      if (_jspx_th_c_005fset_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f6);
      _jspx_th_c_005fset_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/order/orderGoodsForm.jsp(33,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      // /WEB-INF/views/order/orderGoodsForm.jsp(33,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/order/orderGoodsForm.jsp(33,7) '${myOrderList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${myOrderList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\r\n");
            out.write("								<a\r\n");
            out.write("									href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/goods/goodsDetail.do?goods_id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.goods_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("									class=\"shadow-sm p-0 mt-3 rounded border border-light d-flex justify-content-between text-decoration-none\">\r\n");
            out.write("									<div class=\"d-flex\">\r\n");
            out.write("										<div class=\"d-flex align-items-center p-4\">\r\n");
            out.write("											<div class=\"d-flex justify-content-between\">\r\n");
            out.write("												<div class=\"d-flex\">\r\n");
            out.write("\r\n");
            out.write("													<!-- 상품이미지 -->\r\n");
            out.write("													<img\r\n");
            out.write("														src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/thumbnails.do?goods_id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.goods_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&fileName=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.goods_fileName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("														width=\"64px\">\r\n");
            out.write("													<!-- 상품이미지 -->\r\n");
            out.write("\r\n");
            out.write("													<!-- 상품id와 filename등 사용자에게 보여주지않아도 되는 정보들은 hidden type으로 넘긴다. -->\r\n");
            out.write("													<input type=\"hidden\" id=\"h_goods_id\" name=\"h_goods_id\"\r\n");
            out.write("														value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.goods_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" /> <input type=\"hidden\"\r\n");
            out.write("														id=\"h_goods_fileName\" name=\"h_goods_fileName\"\r\n");
            out.write("														value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.goods_fileName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" />\r\n");
            out.write("\r\n");
            out.write("													<div class=\"ms-3\">\r\n");
            out.write("\r\n");
            out.write("														<!-- 상품이름 -->\r\n");
            out.write("														<p class=\"mb-1 mt-1 small\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.goods_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("														<input type=\"hidden\" id=\"h_goods_title\"\r\n");
            out.write("															name=\"h_goods_title\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.goods_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" />\r\n");
            out.write("														<!-- 상품이름 -->\r\n");
            out.write("\r\n");
            out.write("														<!-- 상품가격 표시-->\r\n");
            out.write("														<p class=\"mb-0 text-secondary\">\r\n");
            out.write("															<!-- 상품 낱개가격 -->\r\n");
            out.write("															<span>\r\n");
            out.write("															");
            if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("															</span> 원 <span> ·\r\n");
            out.write("															</span> <input type=\"hidden\" id=\"h_each_goods_price\"\r\n");
            out.write("																name=\"h_each_goods_price\"\r\n");
            out.write("																value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.goods_price * item.order_goods_qty}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" />\r\n");
            out.write("															<!-- 상품 낱개가격 -->\r\n");
            out.write("\r\n");
            out.write("															<!-- 상품수량 -->\r\n");
            out.write("															<span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.order_goods_qty }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>개 <input\r\n");
            out.write("																type=\"hidden\" id=\"h_order_goods_qty\"\r\n");
            out.write("																name=\"h_order_goods_qty\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.order_goods_qty}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" />\r\n");
            out.write("															<!-- 상품수량 -->\r\n");
            out.write("\r\n");
            out.write("															<!-- 상품별 총 가격: 낱개가격*수량, 필요없는 정보라고 생각하여 주석처리, 추후 필요할 경우 사용한다. -->\r\n");
            out.write("															");
            out.write("\r\n");
            out.write("															<!-- 상품별 총 가격: 낱개가격*수량, 필요없는 정보라고 생각하여 주석처리, 추후 필요할 경우 사용한다. -->\r\n");
            out.write("\r\n");
            out.write("														</p>\r\n");
            out.write("														<!-- 상품가격 표시 -->\r\n");
            out.write("\r\n");
            out.write("													</div>\r\n");
            out.write("												</div>\r\n");
            out.write("											</div>\r\n");
            out.write("										</div>\r\n");
            out.write("									</div>\r\n");
            out.write("								</a>\r\n");
            out.write("\r\n");
            out.write("								<!-- 상품 가격정보 -->\r\n");
            out.write("								");
            if (_jspx_meth_c_005fset_005f7(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("								");
            if (_jspx_meth_c_005fset_005f8(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("								");
            if (_jspx_meth_c_005fset_005f9(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("								<!-- 상품 가격정보 -->\r\n");
            out.write("\r\n");
            out.write("							");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/order/orderGoodsForm.jsp(67,15) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.goods_price}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/order/orderGoodsForm.jsp(67,15) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setPattern("#,###");
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f7 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f7_reused = false;
    try {
      _jspx_th_c_005fset_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/order/orderGoodsForm.jsp(95,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f7.setVar("final_total_order_price");
      // /WEB-INF/views/order/orderGoodsForm.jsp(95,8) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f7.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/order/orderGoodsForm.jsp(95,8) '${final_total_order_price+ item.goods_price* item.order_goods_qty}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${final_total_order_price+ item.goods_price* item.order_goods_qty}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f7 = _jspx_th_c_005fset_005f7.doStartTag();
      if (_jspx_th_c_005fset_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f7);
      _jspx_th_c_005fset_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f8 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f8_reused = false;
    try {
      _jspx_th_c_005fset_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/order/orderGoodsForm.jsp(97,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f8.setVar("total_order_price");
      // /WEB-INF/views/order/orderGoodsForm.jsp(97,8) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f8.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/order/orderGoodsForm.jsp(97,8) '${total_order_price+ item.goods_price* item.order_goods_qty}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${total_order_price+ item.goods_price* item.order_goods_qty}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f8 = _jspx_th_c_005fset_005f8.doStartTag();
      if (_jspx_th_c_005fset_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f8);
      _jspx_th_c_005fset_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f8, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f9 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f9_reused = false;
    try {
      _jspx_th_c_005fset_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/order/orderGoodsForm.jsp(99,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f9.setVar("total_order_goods_qty");
      // /WEB-INF/views/order/orderGoodsForm.jsp(99,8) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f9.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/order/orderGoodsForm.jsp(99,8) '${total_order_goods_qty+item.order_goods_qty }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${total_order_goods_qty+item.order_goods_qty }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f9 = _jspx_th_c_005fset_005f9.doStartTag();
      if (_jspx_th_c_005fset_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f9);
      _jspx_th_c_005fset_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f9, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f1.setParent(null);
      // /WEB-INF/views/order/orderGoodsForm.jsp(114,8) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${total_order_price}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/order/orderGoodsForm.jsp(114,8) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setPattern("#,###");
      int _jspx_eval_fmt_005fformatNumber_005f1 = _jspx_th_fmt_005fformatNumber_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f1);
      _jspx_th_fmt_005fformatNumber_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f2 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f2_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f2.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f2.setParent(null);
      // /WEB-INF/views/order/orderGoodsForm.jsp(126,9) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${final_total_order_price }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/order/orderGoodsForm.jsp(126,9) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f2.setPattern("#,###");
      int _jspx_eval_fmt_005fformatNumber_005f2 = _jspx_th_fmt_005fformatNumber_005f2.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f2);
      _jspx_th_fmt_005fformatNumber_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f2, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f10 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f10_reused = false;
    try {
      _jspx_th_c_005fset_005f10.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f10.setParent(null);
      // /WEB-INF/views/order/orderGoodsForm.jsp(168,50) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f10.setVar("orderer_hp");
      // /WEB-INF/views/order/orderGoodsForm.jsp(168,50) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f10.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/order/orderGoodsForm.jsp(168,50) '${orderer.hp1}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${orderer.hp1}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f10 = _jspx_th_c_005fset_005f10.doStartTag();
      if (_jspx_th_c_005fset_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f10);
      _jspx_th_c_005fset_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f10, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f10_reused);
    }
    return false;
  }
}
